version: 2
jobs:
  build:
    branches:
        only:
            - develop
    docker:
      - image: circleci/node:lts
      - image: python:3.4.4
      - image: circleci/python:3.4-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Karma Tests
          command: npm test
