version: 2
jobs:
  build:
    branches:
        only:
            - develop
    docker:
      - image: circleci/node:lts
      - image: circleci/python:3.4-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Karma Tests
          command: npm test
